Create hu.json
outsideris/slack-invite-automation pull request #112
Opened 2017-11-02 10:07 UTC by sajt

issue #111

2017-11-02 10:14 UTC, aboros requested changes

2017-11-02 10:14 UTC, aboros commented on locales/hu.json
> +  "TITLE": "Csatlakozz a %s társaságjoz a Slack-en!"
typo in: társaságjoz
replace with: társasághoz

2017-11-03 11:40 UTC, outsideris commented
Can you add supported language on README?

2017-12-10 14:47 UTC, outsideris commented
I will close this because @sajt didn't come back anymore. I will accept somebody makes new PR for Hungarian.

2017-12-10 14:47 UTC, closed without merging